name:
  default config ddp for mnist

training:
  batch_size: 1024
  epochs: 500
  lr: 1e-3
  logit_sampling: false
  device: cuda
  save_model: true
  wandb_offline: false
  dataset_fraction: 0.2
  project_name: reflow1
  dataset: cifar10  # mnist, cifar10
  optimizer: Adam

model:
  hidden_dim: 128
  depth: 12
  num_heads: 8
  qkv_bias: true
  patch_size: 2
  num_channels: 3
  input_size: 32
  num_classes: 10
  cfg_dropout_prob: 0.2

distributed:
  enabled: false
  world_size: 1
