name:
  default config ddp for cifar

training:
  batch_size: 256
  epochs: 500
  lr: 1e-3
  logit_sampling: true
  device: cuda
  save_model: true
  wandb_offline: false
  dataset_fraction: 0.2
  project_name: reflow1
  dataset: cifar10  # mnist, cifar10
  optimizer: AdamW

model:
  hidden_dim: 256
  depth: 10
  num_heads: 8
  qkv_bias: false
  patch_size: 2
  num_channels: 3
  input_size: 32
  num_classes: 10
  cfg_dropout_prob: 0.2

distributed:
  enabled: true
  world_size: 2
