name:
  default config ddp for mnist

training:
  batch_size: 1024
  epochs: 100
  lr: 1e-3
  logit_sampling: true
  device: cuda
  save_model: true
  wandb_offline: false
  dataset_fraction: 0.25
  project_name: reflow1
  dataset: mnist  # mnist, cifar10
  optimizer: AdamW

model:
  hidden_dim: 64
  depth: 8
  num_heads: 4
  qkv_bias: false
  patch_size: 2
  num_channels: 1
  input_size: 28
  num_classes: 10
  cfg_dropout_prob: 0.1

distributed:
  enabled: false
  world_size: 1
