program: ddp_train.py
name: cifar1
project: reflow-cifar10
method: grid
parameters:
  lr:
    value: 0.001
  batch_size:
    value: 100
  timesteps:
    value: 30
  patch_size:
    value: 32
  dataset_fraction:
    value: 0.2
  depth:
    value: 8
  num_heads:
    value: 8
  hidden_dim:
    value: 64
  epochs:
    value: 50
  dataset:
    value: cifar10
  num_channels:
    value: 3
  input_size:
    value: 32
  ddp:
    value: true

command:
  - ${interpreter}
  - ${program}
  - ${args}
